package androidx.compose.material.icons.twotone;

import androidx.compose.material.icons.Icons;
import androidx.compose.ui.graphics.Brush;
import androidx.compose.ui.graphics.Color;
import androidx.compose.ui.graphics.SolidColor;
import androidx.compose.ui.graphics.StrokeCap;
import androidx.compose.ui.graphics.StrokeJoin;
import androidx.compose.ui.graphics.vector.ImageVector;
import androidx.compose.ui.graphics.vector.PathBuilder;
import androidx.compose.ui.graphics.vector.VectorKt;
import androidx.compose.ui.unit.Dp;
import kotlin.Metadata;
import kotlin.Unit;
import kotlin.jvm.internal.DefaultConstructorMarker;
import kotlin.jvm.internal.Intrinsics;

@Metadata(d1 = {"\u0000\u0010\n\u0000\n\u0002\u0018\u0002\n\u0000\n\u0002\u0018\u0002\n\u0002\b\u0003\"\u0010\u0010\u0000\u001a\u0004\u0018\u00010\u0001X\u000e¢\u0006\u0002\n\u0000\"\u0015\u0010\u0002\u001a\u00020\u0001*\u00020\u00038F¢\u0006\u0006\u001a\u0004\b\u0004\u0010\u0005¨\u0006\u0006"}, d2 = {"_qrCode", "Landroidx/compose/ui/graphics/vector/ImageVector;", "QrCode", "Landroidx/compose/material/icons/Icons$TwoTone;", "getQrCode", "(Landroidx/compose/material/icons/Icons$TwoTone;)Landroidx/compose/ui/graphics/vector/ImageVector;", "material-icons-extended-twotone_release"}, k = 2, mv = {1, 8, 0}, xi = 48)
/* compiled from: QrCode.kt */
public final class QrCodeKt {
    private static ImageVector _qrCode;

    public static final ImageVector getQrCode(Icons.TwoTone twoTone) {
        Intrinsics.checkNotNullParameter(twoTone, "<this>");
        ImageVector imageVector = _qrCode;
        if (imageVector != null) {
            Intrinsics.checkNotNull(imageVector);
            return imageVector;
        }
        ImageVector.Builder builder = r1;
        ImageVector.Builder builder2 = r1;
        ImageVector.Builder builder3 = r1;
        ImageVector.Builder builder4 = r1;
        ImageVector.Builder builder5 = r1;
        ImageVector.Builder builder6 = r1;
        ImageVector.Builder builder7 = r1;
        ImageVector.Builder builder8 = r1;
        ImageVector.Builder builder9 = r1;
        ImageVector.Builder builder10 = r1;
        ImageVector.Builder builder11 = r1;
        ImageVector.Builder builder12 = r1;
        ImageVector.Builder builder13 = r1;
        ImageVector.Builder builder14 = r1;
        ImageVector.Builder builder15 = new ImageVector.Builder("TwoTone.QrCode", Dp.m5626constructorimpl(24.0f), Dp.m5626constructorimpl(24.0f), 24.0f, 24.0f, 0, 0, false, 224, (DefaultConstructorMarker) null);
        int r22 = StrokeCap.Companion.m3204getButtKaPHkGw();
        int r23 = StrokeJoin.Companion.m3214getBevelLxFBmk8();
        PathBuilder pathBuilder = new PathBuilder();
        pathBuilder.moveTo(5.0f, 15.0f);
        pathBuilder.horizontalLineToRelative(4.0f);
        pathBuilder.verticalLineToRelative(4.0f);
        pathBuilder.horizontalLineToRelative(-4.0f);
        pathBuilder.close();
        Unit unit = Unit.INSTANCE;
        ImageVector.Builder.m3530addPathoIyEayM$default(builder14, pathBuilder.getNodes(), VectorKt.getDefaultFillType(), "", new SolidColor(Color.Companion.m2847getBlack0d7_KjU(), (DefaultConstructorMarker) null), 0.3f, (Brush) null, 0.3f, 1.0f, r22, r23, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null);
        int r39 = StrokeCap.Companion.m3204getButtKaPHkGw();
        int r40 = StrokeJoin.Companion.m3214getBevelLxFBmk8();
        PathBuilder pathBuilder2 = new PathBuilder();
        pathBuilder2.moveTo(5.0f, 5.0f);
        pathBuilder2.horizontalLineToRelative(4.0f);
        pathBuilder2.verticalLineToRelative(4.0f);
        pathBuilder2.horizontalLineToRelative(-4.0f);
        pathBuilder2.close();
        Unit unit2 = Unit.INSTANCE;
        ImageVector.Builder.m3530addPathoIyEayM$default(builder13, pathBuilder2.getNodes(), VectorKt.getDefaultFillType(), "", new SolidColor(Color.Companion.m2847getBlack0d7_KjU(), (DefaultConstructorMarker) null), 0.3f, (Brush) null, 0.3f, 1.0f, r39, r40, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null);
        int r56 = StrokeCap.Companion.m3204getButtKaPHkGw();
        int r57 = StrokeJoin.Companion.m3214getBevelLxFBmk8();
        PathBuilder pathBuilder3 = new PathBuilder();
        pathBuilder3.moveTo(15.0f, 5.0f);
        pathBuilder3.horizontalLineToRelative(4.0f);
        pathBuilder3.verticalLineToRelative(4.0f);
        pathBuilder3.horizontalLineToRelative(-4.0f);
        pathBuilder3.close();
        Unit unit3 = Unit.INSTANCE;
        ImageVector.Builder.m3530addPathoIyEayM$default(builder12, pathBuilder3.getNodes(), VectorKt.getDefaultFillType(), "", new SolidColor(Color.Companion.m2847getBlack0d7_KjU(), (DefaultConstructorMarker) null), 0.3f, (Brush) null, 0.3f, 1.0f, r56, r57, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null);
        int r73 = StrokeCap.Companion.m3204getButtKaPHkGw();
        int r74 = StrokeJoin.Companion.m3214getBevelLxFBmk8();
        PathBuilder pathBuilder4 = new PathBuilder();
        pathBuilder4.moveTo(3.0f, 11.0f);
        pathBuilder4.horizontalLineToRelative(8.0f);
        pathBuilder4.verticalLineTo(3.0f);
        pathBuilder4.horizontalLineTo(3.0f);
        pathBuilder4.verticalLineTo(11.0f);
        pathBuilder4.close();
        pathBuilder4.moveTo(5.0f, 5.0f);
        pathBuilder4.horizontalLineToRelative(4.0f);
        pathBuilder4.verticalLineToRelative(4.0f);
        pathBuilder4.horizontalLineTo(5.0f);
        pathBuilder4.verticalLineTo(5.0f);
        pathBuilder4.close();
        Unit unit4 = Unit.INSTANCE;
        ImageVector.Builder.m3530addPathoIyEayM$default(builder11, pathBuilder4.getNodes(), VectorKt.getDefaultFillType(), "", new SolidColor(Color.Companion.m2847getBlack0d7_KjU(), (DefaultConstructorMarker) null), 1.0f, (Brush) null, 1.0f, 1.0f, r73, r74, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null);
        int r90 = StrokeCap.Companion.m3204getButtKaPHkGw();
        int r91 = StrokeJoin.Companion.m3214getBevelLxFBmk8();
        PathBuilder pathBuilder5 = new PathBuilder();
        pathBuilder5.moveTo(3.0f, 21.0f);
        pathBuilder5.horizontalLineToRelative(8.0f);
        pathBuilder5.verticalLineToRelative(-8.0f);
        pathBuilder5.horizontalLineTo(3.0f);
        pathBuilder5.verticalLineTo(21.0f);
        pathBuilder5.close();
        pathBuilder5.moveTo(5.0f, 15.0f);
        pathBuilder5.horizontalLineToRelative(4.0f);
        pathBuilder5.verticalLineToRelative(4.0f);
        pathBuilder5.horizontalLineTo(5.0f);
        pathBuilder5.verticalLineTo(15.0f);
        pathBuilder5.close();
        Unit unit5 = Unit.INSTANCE;
        ImageVector.Builder.m3530addPathoIyEayM$default(builder10, pathBuilder5.getNodes(), VectorKt.getDefaultFillType(), "", new SolidColor(Color.Companion.m2847getBlack0d7_KjU(), (DefaultConstructorMarker) null), 1.0f, (Brush) null, 1.0f, 1.0f, r90, r91, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null);
        int r107 = StrokeCap.Companion.m3204getButtKaPHkGw();
        int r108 = StrokeJoin.Companion.m3214getBevelLxFBmk8();
        PathBuilder pathBuilder6 = new PathBuilder();
        pathBuilder6.moveTo(13.0f, 3.0f);
        pathBuilder6.verticalLineToRelative(8.0f);
        pathBuilder6.horizontalLineToRelative(8.0f);
        pathBuilder6.verticalLineTo(3.0f);
        pathBuilder6.horizontalLineTo(13.0f);
        pathBuilder6.close();
        pathBuilder6.moveTo(19.0f, 9.0f);
        pathBuilder6.horizontalLineToRelative(-4.0f);
        pathBuilder6.verticalLineTo(5.0f);
        pathBuilder6.horizontalLineToRelative(4.0f);
        pathBuilder6.verticalLineTo(9.0f);
        pathBuilder6.close();
        Unit unit6 = Unit.INSTANCE;
        ImageVector.Builder.m3530addPathoIyEayM$default(builder9, pathBuilder6.getNodes(), VectorKt.getDefaultFillType(), "", new SolidColor(Color.Companion.m2847getBlack0d7_KjU(), (DefaultConstructorMarker) null), 1.0f, (Brush) null, 1.0f, 1.0f, r107, r108, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null);
        int r124 = StrokeCap.Companion.m3204getButtKaPHkGw();
        int r125 = StrokeJoin.Companion.m3214getBevelLxFBmk8();
        PathBuilder pathBuilder7 = new PathBuilder();
        pathBuilder7.moveTo(19.0f, 19.0f);
        pathBuilder7.horizontalLineToRelative(2.0f);
        pathBuilder7.verticalLineToRelative(2.0f);
        pathBuilder7.horizontalLineToRelative(-2.0f);
        pathBuilder7.close();
        Unit unit7 = Unit.INSTANCE;
        ImageVector.Builder.m3530addPathoIyEayM$default(builder8, pathBuilder7.getNodes(), VectorKt.getDefaultFillType(), "", new SolidColor(Color.Companion.m2847getBlack0d7_KjU(), (DefaultConstructorMarker) null), 1.0f, (Brush) null, 1.0f, 1.0f, r124, r125, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null);
        int r141 = StrokeCap.Companion.m3204getButtKaPHkGw();
        int r142 = StrokeJoin.Companion.m3214getBevelLxFBmk8();
        PathBuilder pathBuilder8 = new PathBuilder();
        pathBuilder8.moveTo(13.0f, 13.0f);
        pathBuilder8.horizontalLineToRelative(2.0f);
        pathBuilder8.verticalLineToRelative(2.0f);
        pathBuilder8.horizontalLineToRelative(-2.0f);
        pathBuilder8.close();
        Unit unit8 = Unit.INSTANCE;
        ImageVector.Builder.m3530addPathoIyEayM$default(builder7, pathBuilder8.getNodes(), VectorKt.getDefaultFillType(), "", new SolidColor(Color.Companion.m2847getBlack0d7_KjU(), (DefaultConstructorMarker) null), 1.0f, (Brush) null, 1.0f, 1.0f, r141, r142, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null);
        int r158 = StrokeCap.Companion.m3204getButtKaPHkGw();
        int r159 = StrokeJoin.Companion.m3214getBevelLxFBmk8();
        PathBuilder pathBuilder9 = new PathBuilder();
        pathBuilder9.moveTo(15.0f, 15.0f);
        pathBuilder9.horizontalLineToRelative(2.0f);
        pathBuilder9.verticalLineToRelative(2.0f);
        pathBuilder9.horizontalLineToRelative(-2.0f);
        pathBuilder9.close();
        Unit unit9 = Unit.INSTANCE;
        ImageVector.Builder.m3530addPathoIyEayM$default(builder6, pathBuilder9.getNodes(), VectorKt.getDefaultFillType(), "", new SolidColor(Color.Companion.m2847getBlack0d7_KjU(), (DefaultConstructorMarker) null), 1.0f, (Brush) null, 1.0f, 1.0f, r158, r159, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null);
        int r175 = StrokeCap.Companion.m3204getButtKaPHkGw();
        int r176 = StrokeJoin.Companion.m3214getBevelLxFBmk8();
        PathBuilder pathBuilder10 = new PathBuilder();
        pathBuilder10.moveTo(13.0f, 17.0f);
        pathBuilder10.horizontalLineToRelative(2.0f);
        pathBuilder10.verticalLineToRelative(2.0f);
        pathBuilder10.horizontalLineToRelative(-2.0f);
        pathBuilder10.close();
        Unit unit10 = Unit.INSTANCE;
        ImageVector.Builder.m3530addPathoIyEayM$default(builder5, pathBuilder10.getNodes(), VectorKt.getDefaultFillType(), "", new SolidColor(Color.Companion.m2847getBlack0d7_KjU(), (DefaultConstructorMarker) null), 1.0f, (Brush) null, 1.0f, 1.0f, r175, r176, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null);
        int r192 = StrokeCap.Companion.m3204getButtKaPHkGw();
        int r193 = StrokeJoin.Companion.m3214getBevelLxFBmk8();
        PathBuilder pathBuilder11 = new PathBuilder();
        pathBuilder11.moveTo(15.0f, 19.0f);
        pathBuilder11.horizontalLineToRelative(2.0f);
        pathBuilder11.verticalLineToRelative(2.0f);
        pathBuilder11.horizontalLineToRelative(-2.0f);
        pathBuilder11.close();
        Unit unit11 = Unit.INSTANCE;
        ImageVector.Builder.m3530addPathoIyEayM$default(builder4, pathBuilder11.getNodes(), VectorKt.getDefaultFillType(), "", new SolidColor(Color.Companion.m2847getBlack0d7_KjU(), (DefaultConstructorMarker) null), 1.0f, (Brush) null, 1.0f, 1.0f, r192, r193, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null);
        int r209 = StrokeCap.Companion.m3204getButtKaPHkGw();
        int r210 = StrokeJoin.Companion.m3214getBevelLxFBmk8();
        PathBuilder pathBuilder12 = new PathBuilder();
        pathBuilder12.moveTo(17.0f, 17.0f);
        pathBuilder12.horizontalLineToRelative(2.0f);
        pathBuilder12.verticalLineToRelative(2.0f);
        pathBuilder12.horizontalLineToRelative(-2.0f);
        pathBuilder12.close();
        Unit unit12 = Unit.INSTANCE;
        ImageVector.Builder.m3530addPathoIyEayM$default(builder3, pathBuilder12.getNodes(), VectorKt.getDefaultFillType(), "", new SolidColor(Color.Companion.m2847getBlack0d7_KjU(), (DefaultConstructorMarker) null), 1.0f, (Brush) null, 1.0f, 1.0f, r209, r210, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null);
        int r226 = StrokeCap.Companion.m3204getButtKaPHkGw();
        int r227 = StrokeJoin.Companion.m3214getBevelLxFBmk8();
        PathBuilder pathBuilder13 = new PathBuilder();
        pathBuilder13.moveTo(17.0f, 13.0f);
        pathBuilder13.horizontalLineToRelative(2.0f);
        pathBuilder13.verticalLineToRelative(2.0f);
        pathBuilder13.horizontalLineToRelative(-2.0f);
        pathBuilder13.close();
        Unit unit13 = Unit.INSTANCE;
        ImageVector.Builder.m3530addPathoIyEayM$default(builder2, pathBuilder13.getNodes(), VectorKt.getDefaultFillType(), "", new SolidColor(Color.Companion.m2847getBlack0d7_KjU(), (DefaultConstructorMarker) null), 1.0f, (Brush) null, 1.0f, 1.0f, r226, r227, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null);
        int r243 = StrokeCap.Companion.m3204getButtKaPHkGw();
        int r244 = StrokeJoin.Companion.m3214getBevelLxFBmk8();
        PathBuilder pathBuilder14 = new PathBuilder();
        pathBuilder14.moveTo(19.0f, 15.0f);
        pathBuilder14.horizontalLineToRelative(2.0f);
        pathBuilder14.verticalLineToRelative(2.0f);
        pathBuilder14.horizontalLineToRelative(-2.0f);
        pathBuilder14.close();
        Unit unit14 = Unit.INSTANCE;
        ImageVector build = ImageVector.Builder.m3530addPathoIyEayM$default(builder, pathBuilder14.getNodes(), VectorKt.getDefaultFillType(), "", new SolidColor(Color.Companion.m2847getBlack0d7_KjU(), (DefaultConstructorMarker) null), 1.0f, (Brush) null, 1.0f, 1.0f, r243, r244, 1.0f, 0.0f, 0.0f, 0.0f, 14336, (Object) null).build();
        _qrCode = build;
        Intrinsics.checkNotNull(build);
        return build;
    }
}
